version: '3'

services:

  server:
    build:
      context: server
      args:
        - MODEL_NAME=identity
    environment:
      - MODEL_NAME=identity
      - SERVING_PORT=8500
    ports:
      - "8500:8500"

  falcon-client:
    build:
      context: client
      args:
        - MODEL_NAME=identity
    command:
      gunicorn --workers=4 --worker-class=tornado --bind=0.0.0.0:8000 falcon_client:api
    environment:
      - MODEL_NAME=identity
      - SERVING_HOST=server
      - SERVING_PORT=8500
      - CLIENT_PORT=8000
    ports:
      - "8000:8000"
    links:
      - server

  tornado-client:
    build:
      context: client
      args:
        - MODEL_NAME=identity
    command:
      python3 tornado_client.py
    environment:
      - MODEL_NAME=identity
      - SERVING_HOST=server
      - SERVING_PORT=8500
      - CLIENT_PORT=8000
    ports:
      - "8080:8000"
    links:
      - server

  grpc-benchmark:
    build:
      context: client
      args:
        - MODEL_NAME=identity
    command:
      python3 grpc_client.py
    environment:
      - MODEL_NAME=identity
      - SERVING_HOST=server
      - SERVING_PORT=8500
    links:
      - server

  falcon-benchmark:
    build:
      context: client
      args:
        - MODEL_NAME=identity
    command:
      wrk -t12 -c400 -d30s http://client:8000/prediction
    links:
      - server
      - falcon-client:client

  tornado-benchmark:
    build:
      context: client
      args:
        - MODEL_NAME=identity
    command:
      wrk -t12 -c400 -d30s http://client:8000/prediction
    links:
      - server
      - tornado-client:client